fix: fix               # default: false
parallel: true          # default: false
format: progress        # default: Standard::Formatter
ruby_version: 2.7.2     # default: RUBY_VERSION
default_ignores: false  # default: true

ignore:                 # default: []
  - 'db/schema.rb'
  - 'bin/**/*'
  - 'node_modules/**/*'
  - 'config/**/*'
  - 'vendor/**/*'
  - 'Guardfile'